<?php

use Drupal\node\NodeInterface;

/**
 * @file
 * Preprocess functions for Stanford STVP Subtheme.
 */

/**
 * Get the current route's node from the page if one is available.
 *
 * @param string $bundle
 *   Only return the desired node type.
 * @param string $field
 *   Only return the desired node type with a field that is populated.
 *
 * @return \Drupal\node\NodeInterface|null
 */
function _stvp_subtheme_get_route_node(string $bundle = '', string $field = ''): ?NodeInterface {
  $node = &drupal_static(__FUNCTION__ . $bundle . $field);
  if ($node) {
    return $node;
  }

  $node = \Drupal::routeMatch()->getParameter('node');
  if (!$node instanceof NodeInterface) {
    return NULL;
  }
  if ($bundle && $node->bundle() != $bundle) {
    return NULL;
  }
  if ($field && (!$node->hasField($field) || !$node->get($field)->count())) {
    return NULL;
  }
  return $node;
}

function _stvp_subtheme_get_learning_path_tid(): ?int {
  $tid = &drupal_static(__FUNCTION__, NULL);
  if ($tid) {
    return $tid;
  }

  $learningPathTerm = \Drupal::entityTypeManager()
    ->getStorage('taxonomy_term')
    ->loadByProperties([
      'vid' => 'stanford_news_topics',
      'name' => 'Learning Paths',
    ]);
  if (!$learningPathTerm) {
    return NULL;
  }
  return key($learningPathTerm) ?? NULL;
}

/**
 * Implements hook_preprocess_views_view().
 */
function stvp_subtheme_preprocess_views_view(&$variables) {
  if ($variables['id'] == 'stanford_news' && $variables['display_id'] == 'related_spotlights') {
    $node = _stvp_subtheme_get_route_node('stanford_news', 'su_news_topics');
    if (!$node) {
      return;
    }

    $tid = _stvp_subtheme_get_learning_path_tid();
    if (!$tid) {
      return;
    }

    $topics = $node->get('su_news_topics')->getValue();
    foreach ($topics as $topic) {
      if ($topic['target_id'] == $tid) {
        $variables['header']['area_text_custom']['#markup'] = '<h2>More Learning Paths</h2>';
        return;
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stvp_subtheme_preprocess_block__simple_block__su_spotlight_label(&$variables) {
  $node = _stvp_subtheme_get_route_node('stanford_news', 'su_news_topics');
  if (!$node) {
    return;
  }

  $tid = _stvp_subtheme_get_learning_path_tid();
  if (!$tid) {
    return;
  }

  $topics = $node->get('su_news_topics')->getValue();
  foreach ($topics as $topic) {
    if ($topic['target_id'] == $tid) {
      $variables['content']['#text'] = '<p>Learning Path</p>';
      return;
    }
  }
}

/**
 * Prepares variables for the html.html.twig template.
 */
function stvp_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')
    ->getPath('stanford_basic');

  // Add page theme class to body if page title banner present
  $node = _stvp_subtheme_get_route_node('stanford_page', 'su_page_banner');
  if (!$node) {
    return;
  }
  $paragraphs = $node->get('su_page_banner')->referencedEntities();

  foreach ($paragraphs as $paragraph) {
    if ($paragraph && $paragraph->bundle() == 'stanford_page_title_banner') {
      $title_class = $paragraph->getBehaviorSetting('react_paragraphs:page_title_banner_info', 'title_style');
      if ($title_class) {
        $existing_classes = $variables['attributes']['class'] ?? [];
        $variables['attributes']['class'] = array_merge($existing_classes, [$title_class]);

        // If the title style contains 'ecorner', hide the page h1 visually.
        if (str_contains($title_class, 'ecorner')) {
          // Attach the ecorner library to add the JS for hiding the h1.
          $variables['#attached']['library'][] = 'stvp_subtheme/ecorner';
        }

        break;
      }
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function stvp_subtheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'stvp_subtheme_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stvp_subtheme_preprocess_paragraph__stanford_page_title_banner(&$variables) {
  $paragraph = $variables['paragraph'];

  // Add variant classes to banner
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:page_title_banner_info', 'title_style');
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:page_title_banner_info', 'title_wave');

  if ($paragraph->getBehaviorSetting('react_paragraphs:page_title_banner_info', 'ecorner_option')) {
    $variables['attributes']['class'][] = 'ecorner';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stvp_subtheme_preprocess_paragraph__stanford_banner(&$variables) {
  $paragraph = $variables['paragraph'];
  // Add variant classes to banner
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:banner_variant_info', 'banner_style');
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:banner_variant_info', 'banner_wave');
}

function stvp_subtheme_preprocess_paragraph__stanford_layout(array &$variables): void {
  /** @var \Drupal\paragraphs\Layout\Paragraph $paragraph */
  $paragraph = &$variables['paragraph'];
  $existing_classes = $variables['attributes']['class'] ?? [];
  $extra_classes = [
    $paragraph->getBehaviorSetting('react_paragraphs:layout_variant_info', 'section_wave'),
  ];
  $variables['attributes']['class'] = array_merge($existing_classes, $extra_classes);
}

function stvp_subtheme_preprocess_paragraph__stanford_wysiwyg(&$variables) {
  $paragraph = $variables['paragraph'];
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:tinted_background', 'tinted_background', 'stvp-text-background--none');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stvp_subtheme_preprocess_block__pdb_component__media_search(&$variables) {
  $algolia_settings = _stvp_algolia_settings();
  if (!$algolia_settings) {
    return;
  }
  $variables['#attached']['drupalSettings']['stanfordAlgolia'] = $algolia_settings;
}

function _stvp_algolia_settings() {
  $settings = &drupal_static(__FUNCTION__);
  if ($settings != NULL) {
    return $settings;
  }

  if (!\Drupal::hasService('config_pages.loader')) {
    return $settings = FALSE;
  }

  /** @var \Drupal\config_pages\ConfigPagesLoaderServiceInterface $config_page */
  $config_page = \Drupal::service('config_pages.loader');

  $algolia_app = $config_page->getValue('stanford_basic_site_settings', 'su_site_algolia_id', 0, 'value');
  $algolia_search_key = $config_page->getValue('stanford_basic_site_settings', 'su_site_algolia_search', 0, 'value');
  $search_index = $config_page->getValue('stanford_basic_site_settings', 'su_site_algolia_index', 0, 'value');
  $federated = (bool) $config_page->getValue('stanford_basic_site_settings', 'su_site_algolia_fed', 0, 'value');
  $settings = [
    'appId' => $algolia_app,
    'searchKey' => $algolia_search_key,
    'index' => $search_index,
    'federatedSearch' => $federated,
  ];
  return $settings;
}
